inveniosoftware/invenio-requests

.dockerignore
.editorconfig
.tx/config
AUTHORS.rst
CHANGES.rst
CONTRIBUTING.rst
INSTALL.rst
LICENSE
MANIFEST.in
README.rst
invenio_requests/ext.py
invenio_requests/proxies.py
invenio_requests/records/api.py
invenio_requests/records/jsonschemas/requests/request-v1.0.0.json
invenio_requests/records/mappings/v7/request_comments/comment-v1.0.0.json
invenio_requests/records/mappings/v7/requests/request-v1.0.0.json
invenio_requests/services/__init__.py
invenio_requests/services/config.py
invenio_requests/services/services.py
pytest.ini
run-tests.sh
setup.cfg
setup.py
tests/conftest.py
tests/services/comments/conftest.py
tests/services/comments/test_comments_services.py
tests/test_invenio_requests.py

framework: set up the RequestComments test and sections to implement

---

invenio_requests/config.py
invenio_requests/ext.py
invenio_requests/services/comments/config.py
invenio_requests/services/comments/customization.py
invenio_requests/services/requests/config.py
invenio_requests/services/requests/customization.py
tests/services/comments/test_comments_service_config.py
tests/services/requests/test_requests_service_config.py

apply the same customization pattern as in `invenio-rdm-records`.
closes #17

services: apply customization pattern like in rdm-records

---

invenio_requests/records/actions.py
invenio_requests/records/api.py
invenio_requests/records/dumpers/__init__.py
invenio_requests/records/dumpers/calculated.py
invenio_requests/records/mappings/v6/requests/request-v1.0.0.json
invenio_requests/records/mappings/v7/requests/request-v1.0.0.json
invenio_requests/records/models.py
invenio_requests/records/schema.py
invenio_requests/records/systemfields/__init__.py
invenio_requests/records/systemfields/open_state.py
invenio_requests/services/__init__.py
invenio_requests/services/events/config.py
invenio_requests/services/events/service.py
invenio_requests/services/permissions.py
invenio_requests/services/schemas.py
tests/conftest.py
tests/services/events/test_request_events_service.py

request: rework is_open into a system field and dumper

---

invenio_requests/ext.py
invenio_requests/records/api.py
invenio_requests/records/mappings/v7/request_events/event-v1.0.0.json
invenio_requests/resources/events/__init__.py
invenio_requests/resources/events/resources.py
invenio_requests/resources/resource.py
invenio_requests/services/events/config.py
invenio_requests/services/events/service.py
invenio_requests/services/permissions.py
invenio_requests/services/schemas.py
invenio_requests/views.py
setup.py
tests/conftest.py
tests/resources/events/conftest.py
tests/resources/events/test_request_events_resources.py
tests/services/events/test_request_events_service.py
tests/services/events/test_request_events_service_config.py

RequestEvent: implement REST API

---

invenio_requests/resources/events/resources.py
invenio_requests/services/events/config.py
invenio_requests/services/events/service.py
tests/resources/events/test_request_events_resources.py

closes: https://github.com/inveniosoftware/invenio-requests/issues/40

RequestEvent: dump search links

---

invenio_requests/resources/events/__init__.py
invenio_requests/resources/events/config.py
invenio_requests/resources/events/resources.py
invenio_requests/services/events/service.py
invenio_requests/services/permissions.py
invenio_requests/services/requests/service.py
tests/services/requests/test_requests_service.py

Polish RequestEvent

---

invenio_requests/resources/events/resource.py
invenio_requests/resources/requests/resource.py
invenio_requests/services/schemas.py
tests/resources/events/test_request_events_resources.py
tests/resources/requests/conftest.py
tests/resources/requests/test_requests_resources.py
tests/services/requests/test_requests_service.py

RequestAction/Comment: validate empty payloads appropriately

---

invenio_requests/records/api.py
invenio_requests/records/jsonschemas/request_events/event-v1.0.0.json
invenio_requests/records/mappings/v6/request_events/event-v1.0.0.json
invenio_requests/records/mappings/v7/request_events/event-v1.0.0.json
invenio_requests/services/events/config.py
invenio_requests/services/events/service.py
invenio_requests/services/permissions.py
setup.cfg
tests/conftest.py
tests/customizations/test_request_types.py
tests/resources/events/test_request_events_resources.py
tests/resources/requests/test_requests_resources.py
tests/services/conftest.py
tests/services/events/test_event_permissions.py
tests/services/events/test_request_events_service.py
tests/services/requests/test_request_permissions.py
tests/services/requests/test_requests_service.py

closes https://github.com/inveniosoftware/invenio-requests/issues/87 Part I

permissions: enforce request action and create comment permissions

---

invenio_requests/records/jsonschemas/requests/request-v1.0.0.json
invenio_requests/services/events/service.py
invenio_requests/services/permissions.py
invenio_requests/services/requests/components.py
invenio_requests/services/requests/config.py
invenio_requests/services/requests/service.py
invenio_requests/services/schemas.py
tests/conftest.py
tests/resources/events/test_request_events_resources.py
tests/resources/requests/test_requests_resources.py
tests/services/conftest.py
tests/services/events/test_event_permissions.py
tests/services/events/test_request_events_service.py
tests/services/requests/test_request_permissions.py
tests/services/requests/test_request_search_permissions.py
tests/services/requests/test_requests_service.py

- search permission is missing
- closes #87 
- closes #29

87 permissions part 2

---

invenio_requests/version.py
setup.py

- part of Align method interface for read and read_many invenio-records-resources#258 (to be in sync)

dependencies: bump records-resources for change in method parameters order

---

invenio_requests/services/requests/results.py

requests: fix RequestItem.__getitem__

---

invenio_requests/customizations/default/request_types.py
invenio_requests/ext.py
invenio_requests/records/systemfields/request_type.py
invenio_requests/services/schemas.py
tests/services/requests/test_requests_schemas.py
tests/services/requests/test_requests_service.py

- tests: add requests_service update test
- tests: add request schemas tests
- closes #96 : False alarm in the end, but that was confirmed with tests :smiley_cat:

96 request service limit update

---

invenio_requests/config.py
invenio_requests/resources/requests/config.py
invenio_requests/services/requests/config.py
invenio_requests/services/requests/facets.py
invenio_requests/services/requests/params.py
tests/test_alembic.py

Service: add facets

---

setup.py
tests/test_alembic.py

* Caused by Invenio-Files-REST partial index.

tests: fix alembic test failure

---

invenio_requests/assets/semantic-ui/js/invenio_requests/request/RequestMetadata.js
invenio_requests/assets/semantic-ui/js/invenio_requests/timelineEvent/TimelineEvent.js

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1284

placeholder: replace with square-placeholder

---

.tx/config
MANIFEST.in
babel.ini
invenio_requests/assets/semantic-ui/js/invenio_requests/components/Buttons.js
invenio_requests/assets/semantic-ui/js/invenio_requests/components/CreatorList.js
invenio_requests/assets/semantic-ui/js/invenio_requests/components/Error.js
invenio_requests/assets/semantic-ui/js/invenio_requests/confirmationModal/ConfirmationModal.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/RequestDetails.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/RequestMetadata.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestAction.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestActionModal.js
invenio_requests/assets/semantic-ui/js/invenio_requests/timelineCommentEditor/TimelineCommentEditor.js
invenio_requests/assets/semantic-ui/js/invenio_requests/timelineEvent/TimelineEvent.js
invenio_requests/assets/semantic-ui/js/invenio_requests/timelineEventWithState/TimelineEventWithState.js
invenio_requests/assets/semantic-ui/translations/invenio_requests/i18next-scanner.config.js
invenio_requests/assets/semantic-ui/translations/invenio_requests/i18next.js
invenio_requests/assets/semantic-ui/translations/invenio_requests/messages/en/translations.json
invenio_requests/assets/semantic-ui/translations/invenio_requests/messages/index.js
invenio_requests/assets/semantic-ui/translations/invenio_requests/messages/pl/messages.po
invenio_requests/assets/semantic-ui/translations/invenio_requests/messages/pl/translations.json
invenio_requests/assets/semantic-ui/translations/invenio_requests/package-lock.json
invenio_requests/assets/semantic-ui/translations/invenio_requests/package.json
invenio_requests/assets/semantic-ui/translations/invenio_requests/scripts/compileCatalog.js
invenio_requests/assets/semantic-ui/translations/invenio_requests/scripts/initCatalog.js
invenio_requests/assets/semantic-ui/translations/invenio_requests/translations.pot
invenio_requests/translations/en/LC_MESSAGES/messages.po
invenio_requests/translations/messages.pot
invenio_requests/translations/pl/LC_MESSAGES/messages.po
invenio_requests/webpack.py

global: add translations support

---

babel.ini
invenio_requests/assets/semantic-ui/translations/.gitignore
invenio_requests/assets/semantic-ui/translations/invenio_requests/messages/de/messages.po
invenio_requests/assets/semantic-ui/translations/invenio_requests/messages/de/translations.json
invenio_requests/assets/semantic-ui/translations/invenio_requests/package.json
invenio_requests/assets/semantic-ui/translations/invenio_requests/translations.pot
invenio_requests/translations/de/LC_MESSAGES/messages.po
invenio_requests/translations/messages.pot

* adds german langugage
* updated translation files
* adds gitignore for ignoring node_modules

i18n: adds german as lang

---

invenio_requests/assets/semantic-ui/js/invenio_requests/InvenioRequestsApp.js
invenio_requests/assets/semantic-ui/js/invenio_requests/api/InvenioRequestApi.js
invenio_requests/assets/semantic-ui/js/invenio_requests/api/InvenioRequestEventsApi.js
invenio_requests/assets/semantic-ui/js/invenio_requests/api/api.js
invenio_requests/assets/semantic-ui/js/invenio_requests/api/index.js
invenio_requests/assets/semantic-ui/js/invenio_requests/components/FormattedInputEditor.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestAction.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestActionModal.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestActions.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/index.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/state/actions.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/state/actions.js

Addresses the comments in https://github.com/inveniosoftware/invenio-requests/issues/142
* closes https://github.com/inveniosoftware/invenio-requests/issues/142
:rotating_light: Please review the [guidelines for contributing](https://invenio.readthedocs.io/en/latest/community/contributing/contribution-guide.html) to Invenio.
> Green light on all GitHub Actions status checks is required in order to merge your PR. Check your code additions will fail neither code linting checks nor tests and will not decrease test coverage.
See [copyright and license policy](https://invenio.readthedocs.io/en/latest/community/contributing/maintainers-guide/copyright-policy.html) for details. …

ui: refactor api and actions buttons

---

invenio_requests/assets/semantic-ui/js/invenio_requests/timelineEvent/TimelineEvent.js

* closes inveniosoftware/invenio-requests#155

Request details: add relative date to comment feed

---

invenio_requests/assets/semantic-ui/js/invenio_requests/InvenioRequestsApp.js
invenio_requests/assets/semantic-ui/js/invenio_requests/api/InvenioRequestEventsApi.js
invenio_requests/assets/semantic-ui/js/invenio_requests/components/Pagination.js
invenio_requests/assets/semantic-ui/js/invenio_requests/index.js
invenio_requests/assets/semantic-ui/js/invenio_requests/timeline/TimelineFeed.js
invenio_requests/assets/semantic-ui/js/invenio_requests/timeline/index.js
invenio_requests/assets/semantic-ui/js/invenio_requests/timeline/state/actions.js
invenio_requests/assets/semantic-ui/js/invenio_requests/timeline/state/reducer.js
invenio_requests/assets/semantic-ui/js/invenio_requests/timelineCommentEditor/state/actions.js
invenio_requests/assets/semantic-ui/less/invenio_requests/theme.less
invenio_requests/config.py
invenio_requests/templates/semantic-ui/invenio_requests/details/index.html
invenio_requests/views/requests.py

Added pagination to the request details conversation 
closes https://github.com/inveniosoftware/invenio-requests/issues/129

Request Details Timeline: pagination

---

invenio_requests/assets/semantic-ui/js/invenio_requests/InvenioRequestsApp.js
invenio_requests/assets/semantic-ui/js/invenio_requests/index.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestActionModal.js
invenio_requests/assets/semantic-ui/js/invenio_requests/requestsAppInit.js
invenio_requests/assets/semantic-ui/js/invenio_requests/store.js
invenio_requests/assets/semantic-ui/js/invenio_requests/timeline/state/reducer.js
invenio_requests/templates/semantic-ui/invenio_requests/details/index.html
invenio_requests/webpack.py

partly closes https://github.com/inveniosoftware/invenio-communities/issues/491

requests: refactor initialization of a request app 

---

invenio_requests/views/requests.py
invenio_requests/views/ui.py

closes https://github.com/inveniosoftware/invenio-requests/issues/186
**Reminder**
1. You license your contribution under the same terms as the current …

views: remove views

---

invenio_requests/__init__.py
invenio_requests/config.py
invenio_requests/customizations/__init__.py
invenio_requests/customizations/actions.py
invenio_requests/customizations/event_types.py
invenio_requests/ext.py
invenio_requests/proxies.py
invenio_requests/records/api.py
invenio_requests/records/systemfields/__init__.py
invenio_requests/records/systemfields/event_type.py
invenio_requests/records/systemfields/request_type.py
invenio_requests/resources/events/resource.py
invenio_requests/services/events/config.py
invenio_requests/services/events/fields.py
invenio_requests/services/events/service.py
invenio_requests/services/requests/service.py
invenio_requests/services/schemas.py
tests/conftest.py
tests/records/events/test_api.py
tests/resources/events/test_request_events_resources.py
tests/services/conftest.py
tests/services/events/conftest.py
tests/services/events/test_event_permissions.py
tests/services/events/test_request_events_service.py
tests/services/requests/test_request_search_permissions.py
tests/services/requests/test_requests_schemas.py
tests/services/requests/test_requests_service.py

refactor request event type

---

invenio_requests/__init__.py

release: v0.3.10

---

invenio_requests/assets/semantic-ui/js/invenio_requests/components/RequestsFeed.js
invenio_requests/assets/semantic-ui/js/invenio_requests/components/TimelineActionEvent.js
invenio_requests/assets/semantic-ui/js/invenio_requests/timelineEvents/TimelineCommentEvent.js
invenio_requests/assets/semantic-ui/js/invenio_requests/timelineEvents/index.js

* refactor RequestsFeeds styling

requests: simplify the components styling

---

invenio_requests/records/systemfields/event_type.py

event_type: remove debugger in comment

---

invenio_requests/assets/semantic-ui/js/invenio_requests/request/IconStatus.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/RequestMetadata.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/RequestStatusIcon.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/index.js
invenio_requests/assets/semantic-ui/js/invenio_requests/requestsAppInit.js

closes: inveniosoftware/invenio-requests#157

RequestDetails: use different icons for each status

---

invenio_requests/tasks.py
tests/services/conftest.py
tests/services/requests/test_requests_service.py
tests/services/requests/test_requests_tasks.py

Addresses https://github.com/inveniosoftware/invenio-communities/issues/505
**Reminder**
2. You agree …

task: add task for expired requests

---

invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestAction.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestActionController.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestActionModal.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/context.js

* closes https://github.com/inveniosoftware/invenio-requests/issues/203

actions: add error handling

---

invenio_requests/config.py
invenio_requests/resolvers/requests.py
invenio_requests/resources/events/resource.py
invenio_requests/resources/requests/resource.py
invenio_requests/services/events/service.py
invenio_requests/services/requests/results.py
invenio_requests/services/requests/service.py
invenio_requests/services/results.py
setup.cfg
tests/resources/events/test_request_events_resources.py

* expand created_by and receiver fields
* adds invenio-users-resources as dependendency
* closes #199
requires https://github.com/inveniosoftware/invenio-records-resources/pull/330

resources: expand referenced fields

---

invenio_requests/templates/semantic-ui/invenio_requests/details/index.html
invenio_requests/views/decorators.py

* enable request details template to handle
custom header changes
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1474

requests details: control request header

---

.github/workflows/pypi-publish.yml
invenio_requests/resources/events/resource.py
invenio_requests/resources/requests/resource.py
setup.cfg
tests/resources/events/test_request_events_resources.py

https://github.com/inveniosoftware/invenio-communities/issues/556

Resources: rename extra view args

---

invenio_requests/assets/semantic-ui/js/invenio_requests/request/RequestDetails.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/RequestMetadata.js
invenio_requests/assets/semantic-ui/js/invenio_requests/timelineCommentEditor/TimelineCommentEditor.js
invenio_requests/assets/semantic-ui/js/invenio_requests/timelineEvents/TimelineCommentEvent.js
invenio_requests/templates/semantic-ui/invenio_requests/details/index.html

Closes https://github.com/inveniosoftware/invenio-requests/issues/204
- Reduced the amount of nested `.ui.container`s, as these are all getting horizontal margins when resizing to tablet and mobile (=> the content becomes very narrow on smaller screens).
- Changed the column widths for mobile/tablet
- Added correct level headings
https://github.com/inveniosoftware/invenio-app-rdm/pull/1523

request details: fix layout bugs and adjust for mobile and tablet

---

invenio_requests/assets/semantic-ui/js/invenio_requests/request/RequestMetadata.js

request metadata: keep aspect ratio of community logo

---

invenio_requests/resources/requests/config.py
invenio_requests/resources/requests/resource.py
invenio_requests/services/permissions.py
invenio_requests/services/requests/config.py
invenio_requests/services/requests/service.py
tests/services/requests/test_requests_service.py

resources: add user requests endpoint

---

invenio_requests/assets/semantic-ui/js/invenio_requests/components/TimelineActionEvent.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/RequestMetadata.js
invenio_requests/assets/semantic-ui/js/invenio_requests/timelineEvents/TimelineCommentEvent.js
invenio_requests/resources/events/resource.py
invenio_requests/resources/requests/resource.py
invenio_requests/services/results.py

* requires: https://github.com/inveniosoftware/invenio-requests/pull/213
* requires: https://github.com/inveniosoftware/invenio-users-resources/pull/33

[EXPAND] ui: change expanded fields

---

invenio_requests/templates/semantic-ui/invenio_requests/details/index.html

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1558
**Needs PR** https://github.com/inveniosoftware/invenio-app-rdm/pull/1560

request details: align request details content

---

invenio_requests/__init__.py
invenio_requests/services/requests/service.py
setup.cfg

- requires https://github.com/inveniosoftware/invenio-records-resources/pull/339
- closes https://github.com/inveniosoftware/invenio-communities/issues/620

service: adapt index refresh op to new api

---

invenio_requests/assets/semantic-ui/js/invenio_requests/components/Buttons.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/RequestMetadata.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestAction.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestActionModal.js
invenio_requests/assets/semantic-ui/js/invenio_requests/requestsAppInit.js
invenio_requests/assets/semantic-ui/translations/invenio_requests/messages/de/translations.json
invenio_requests/assets/semantic-ui/translations/invenio_requests/messages/en/translations.json
invenio_requests/assets/semantic-ui/translations/invenio_requests/messages/pl/translations.json
invenio_requests/assets/semantic-ui/translations/invenio_requests/translations.pot

request: fix modal button text for i18n

---

invenio_requests/assets/semantic-ui/js/invenio_requests/components/Buttons.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestAction.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestActionModal.js

closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1628

request: tweak action button colours

---

invenio_requests/assets/semantic-ui/js/invenio_requests/components/RequestsFeed.js

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1645

avatar: fix alignment

---

invenio_requests/assets/semantic-ui/js/invenio_requests/request/TypeLabel.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestAction.js

request: fix request modal

---

invenio_requests/assets/semantic-ui/js/invenio_requests/request/TypeLabel.js
invenio_requests/services/requests/facets.py

needed by https://github.com/inveniosoftware/invenio-app-rdm/pull/1653

Add request type labels

---

invenio_requests/assets/semantic-ui/js/invenio_requests/InvenioRequestsApp.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/Request.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/RequestDetails.js
invenio_requests/assets/semantic-ui/js/invenio_requests/requestsAppInit.js
invenio_requests/assets/semantic-ui/js/invenio_requests/timeline/TimelineFeed.js
invenio_requests/assets/semantic-ui/js/invenio_requests/timelineCommentEditor/TimelineCommentEditor.js
invenio_requests/templates/semantic-ui/invenio_requests/details/index.html

* closes: inveniosoftware/invenio-app-rdm#1611
Alternative option (requires custom css).

Comment timeline: Add user avatar near edit comment box

---

invenio_requests/assets/semantic-ui/js/invenio_requests/components/Buttons.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestAction.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestActionModal.js

* Add return of action promise
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1215

requestactions: add disabled when loading

---

invenio_requests/templates/semantic-ui/invenio_requests/details/index.html
setup.cfg

- templates: don't override global request in Jinja templates
- extras_require: remove elasticsearch6
- close https://github.com/inveniosoftware/invenio-app-rdm/issues/1668

1668 dont override request

---

invenio_requests/assets/semantic-ui/js/invenio_requests/components/Buttons.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/RequestStatusLabel.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/Status.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/StatusLabel.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestAction.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestActionButton.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestActionController.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestActionModal.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestActionModalTrigger.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestActions.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/index.js
invenio_requests/assets/semantic-ui/js/invenio_requests/requestsAppInit.js
invenio_requests/assets/semantic-ui/less/invenio_requests/theme.less
invenio_requests/templates/semantic-ui/invenio_requests/details/index.html
invenio_requests/webpack.py

closes: https://github.com/inveniosoftware/invenio-communities/issues/702
Desktop:
Tablet:
Mobile:

Requests: re-design requests list view

---

AUTHORS.rst
invenio_requests/resources/events/config.py
invenio_requests/resources/requests/config.py

This PR fix REST-API 500 Internal server error when provide invalid request_id for the following routes:
- GET {{baseURL}}/api/requests/{{request_id}}
- PUT {{baseURL}}/api/requests/{{request_id}}
- POST {{baseURL}}/api/requests/{{request_id}}/actions/accept
- POST {{baseURL}}/api/requests/{{request_id}}/actions/cancel
- POST {{baseURL}}/api/requests/{{request_id}}/actions/decline
- POST {{baseURL}}/api/requests/{{request_id}}/comments
- GET {{baseURL}}/api/requests/{{request_id}}/comments/timeline
It closes [issue 258](https://github.com/inveniosoftware/invenio-requests/issues/258)
If you've added [third-party code (copy/pasted or new …

API: handle errs for invalid request id

---

invenio_requests/assets/semantic-ui/js/invenio_requests/components/Buttons.js
invenio_requests/assets/semantic-ui/js/invenio_requests/components/RequestsFeed.js
invenio_requests/assets/semantic-ui/js/invenio_requests/timelineEvents/timelineActionEvents.js

Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1503
Needs https://github.com/inveniosoftware/invenio-theme/pull/295

global: add general color classes

---

invenio_requests/__init__.py
setup.cfg

release: v0.4.0

---

invenio_requests/__init__.py

release: v0.4.2

---

invenio_requests/assets/semantic-ui/js/invenio_requests/components/Buttons.js
invenio_requests/assets/semantic-ui/js/invenio_requests/components/ModalTriggers.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestAction.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestActionModalTrigger.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestActions.js
invenio_requests/assets/semantic-ui/js/invenio_requests/requestsAppInit.js

Move action buttons to a dropdown.
closes: inveniosoftware/invenio-requests#264

Dashboard requests mobile: center content

---

invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestActions.js

* closes: inveniosoftware/invenio-requests#264

RequestsActions: fix merging issues

---

CHANGES.rst
invenio_requests/__init__.py

release: v1.0.4

---

invenio_requests/services/requests/results.py

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2125

sercices: allow to set links_tpl

---

.gitignore
CHANGES.rst
invenio_requests/__init__.py
invenio_requests/assets/semantic-ui/js/invenio_requests/request/RequestMetadata.js
invenio_requests/config.py
invenio_requests/resolvers/requests.py
invenio_requests/services/results.py
setup.cfg

closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2063

resolve deleted communities

---

invenio_requests/assets/semantic-ui/js/invenio_requests/search/ComputerTabletRequestItem.js
invenio_requests/assets/semantic-ui/js/invenio_requests/search/MobileRequestItem.js
invenio_requests/assets/semantic-ui/js/invenio_requests/search/RequestsResults.js
invenio_requests/assets/semantic-ui/js/invenio_requests/timelineEvents/TimelineCommentEvent.js

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2162

translations: fix string concatenation and pluralizaton

---

invenio_requests/resolvers/requests.py
invenio_requests/services/events/config.py
invenio_requests/services/requests/config.py
invenio_requests/views/__init__.py

resolvers: use record-based resolvers and proxies

---

invenio_requests/assets/semantic-ui/js/invenio_requests/contrib/labels/StatusLabel.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/Status.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestActionModal.js
invenio_requests/customizations/request_types.py
invenio_requests/services/events/service.py
invenio_requests/services/results.py
invenio_requests/templates/semantic-ui/invenio_requests/details/index.html
tests/customizations/test_request_types.py

* closes https://github.com/zenodo/zenodo-rdm/issues/284
Replace non-existing "Expire" icon:
Capitalize the action name in request action modal:
Request details page placeholder preview:

expandable fields: add system record

---

.tx/config

ref https://github.com/inveniosoftware/invenio-i18n/issues/114
Update host info due to deprecation
**Reminder**
1. You license your contribution under the same terms as the current repository’s …

transifex: update host config

---

invenio_requests/assets/semantic-ui/js/invenio_requests/request/RequestMetadata.js

* shows user email if no username or display_name is found and email_visibility != restricted
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2229

ui : fixing username not appearing

---

invenio_requests/assets/semantic-ui/js/invenio_requests/request/RequestMetadata.js
invenio_requests/customizations/request_types.py
invenio_requests/services/requests/links.py

This can be used to fix the wrong "self_html" links.

Make context vars in link generation customizable

---

CHANGES.rst
invenio_requests/__init__.py

release: v2.6.0

---

invenio_requests/assets/semantic-ui/js/invenio_requests/components/ModalTriggers.js
invenio_requests/assets/semantic-ui/js/invenio_requests/contrib/labels/StatusLabel.js
invenio_requests/assets/semantic-ui/js/invenio_requests/contrib/labels/TypeLabel.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestActions.js
invenio_requests/assets/semantic-ui/js/invenio_requests/search/ComputerTabletRequestItem.js
invenio_requests/assets/semantic-ui/js/invenio_requests/search/MobileRequestItem.js
invenio_requests/customizations/request_types.py

Closes https://github.com/inveniosoftware/invenio-requests/issues/328

request items: improve styles

---

CHANGES.rst
invenio_requests/__init__.py

release: v2.6.1

---

CHANGES.rst
invenio_requests/__init__.py
invenio_requests/services/events/service.py

Notify flag will be used by the member invitation, to not trigger several notifications for one invitation.
Implementation of the comment create notification can be found [here](https://github.com/inveniosoftware/invenio-requests/issues/304)
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/ …

services: add notify flag to request event create method

---

invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestActions.js

Closes https://github.com/zenodo/rdm-project/issues/171
Makes dropdown button smaller.

RequestAction: Make dropdown size tiny

---

invenio_requests/assets/semantic-ui/js/invenio_requests/contrib/index.js
invenio_requests/assets/semantic-ui/js/invenio_requests/contrib/labels/TypeLabel.js
invenio_requests/assets/semantic-ui/js/invenio_requests/requestsAppInit.js
invenio_requests/assets/semantic-ui/js/invenio_requests/search/ComputerTabletRequestItem.js
invenio_requests/services/requests/facets.py

closes: https://github.com/inveniosoftware/invenio-rdm-records/issues/1408
1. Opened by: creator email
2. Request type labels
3. Filtering:

ui: fix some ui bugs for access request

---

CHANGES.rst
invenio_requests/__init__.py

release: v2.9.2

---

CHANGES.rst
invenio_requests/__init__.py

release: v2.10.0

---

CHANGES.rst
invenio_requests/__init__.py
invenio_requests/assets/semantic-ui/js/invenio_requests/components/Buttons.js
invenio_requests/assets/semantic-ui/js/invenio_requests/components/ModalTriggers.js
invenio_requests/assets/semantic-ui/js/invenio_requests/components/RequestTypeIcon.js
invenio_requests/assets/semantic-ui/js/invenio_requests/contrib/Icons.js
invenio_requests/assets/semantic-ui/js/invenio_requests/contrib/index.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/RequestMetadata.js
invenio_requests/assets/semantic-ui/js/invenio_requests/search/ComputerTabletRequestItem.js

* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1425

assets: add access request icons

---

invenio_requests/ext.py
invenio_requests/resources/requests/config.py

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2384

resource: add configurable error handlers

---

CHANGES.rst
invenio_requests/__init__.py

release: v2.13.0

---

CHANGES.rst
invenio_requests/__init__.py

release: v2.14.0

---

invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestActionModal.js

Partially Closes [#1022](https://github.com/inveniosoftware/invenio-communities/issues/1022)
**Reminder**
1. You license your contribution under the same terms as the current repository’s …

Community Accept Request Modal Label

---

CHANGES.rst
invenio_requests/__init__.py

release: v2.14.1

---

invenio_requests/notifications/builders.py
invenio_requests/notifications/filters.py
invenio_requests/notifications/generators.py
invenio_requests/templates/semantic-ui/invenio_notifications/comment-request-event.create.jinja

closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1454
depends on
- https://github.com/inveniosoftware/invenio-users-resources/pull/111/files
For guest access requests, the guest should also get notified on comment create. This will resolve a guest or a user properly.
**Reminder** …

notifications: update comment notification to work with email

---

CHANGES.rst
invenio_requests/__init__.py

release: v2.14.3

---

invenio_requests/assets/semantic-ui/js/invenio_requests/timelineEvents/TimelineCommentEvent.js

Closes Issue [#352](https://github.com/zenodo/rdm-project/issues/352)
**Reminder**
2. You agree that you …

ui: fixed styling of comments

---

invenio_requests/templates/semantic-ui/invenio_notifications/comment-request-event.create.jinja

Updated the templates for notification emails
**Reminder**
2. You agree that you have the right to …

emails: updated templates

---

.github/workflows/tests.yml
CHANGES.rst
invenio_requests/__init__.py
invenio_requests/customizations/event_types.py
setup.cfg
tests/conftest.py

- installation: bump records-resources and users-resources
- global: black formatting
- ci: update matrix
- relase: v3.0.0

Bump dependencies and release v3.0.0

---

invenio_requests/assets/semantic-ui/js/invenio_requests/request/RequestMetadata.js

If an entity is different from the ones specified, the component will not render at all. This can happen now, if the receiver or creator is a group. It will resolve successfully on the back end - although without any data.
This PR simply adds an empty default return value.
**Reminder** …

ui: handle default case for EntityDetails

---

invenio_requests/assets/semantic-ui/js/invenio_requests/request/RequestMetadata.js

depends on https://github.com/inveniosoftware/invenio-users-resources/pull/126
Only depends on the linked PR for the data. Otherwise, the group name will be omitted.
Add a group tag for request entities.
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-lice …

ui: add group for EntityDetails

---

invenio_requests/config.py
invenio_requests/services/requests/config.py

config: allow request search configuration

---

invenio_requests/assets/semantic-ui/js/invenio_requests/contrib/index.js
invenio_requests/assets/semantic-ui/js/invenio_requests/contrib/labels/TypeLabel.js
invenio_requests/assets/semantic-ui/js/invenio_requests/requestsAppInit.js

closes https://github.com/zenodo/zenodo-rdm/issues/889

contrib: added subcommunity type label.

---

CHANGES.rst
invenio_requests/__init__.py

- registry: allow entry pointsto be callables

📦 release: v4.4.0

---

invenio_requests/assets/semantic-ui/js/invenio_requests/contrib/labels/TypeLabel.js
invenio_requests/assets/semantic-ui/js/invenio_requests/requestsAppInit.js
invenio_requests/assets/semantic-ui/js/invenio_requests/timelineCommentEditor/TimelineCommentEditor.js
invenio_requests/assets/semantic-ui/js/invenio_requests/timelineEvents/TimelineCommentEvent.js
invenio_requests/config.py
invenio_requests/ext.py
invenio_requests/services/events/service.py
invenio_requests/services/requests/config.py
invenio_requests/services/requests/facets.py

- config: allow request search configuration
- registry: allow entry pointsto be callables
- service: handle request parameters flexibly
- service: fix request ID passing
- ui: [#855] add community membership request label type
- comments: fix jumping cursor

maint v4 1 1 cherry picked

---

invenio_requests/customizations/event_types.py
invenio_requests/resources/events/config.py
invenio_requests/resources/requests/config.py
tests/conftest.py

* closes https://github.com/zenodo/rdm-project/issues/598

http headers: use and adjust vnd.inveniordm.v1+json http accept header

---

invenio_requests/assets/semantic-ui/js/invenio_requests/search/RequestsResults.js

* closes https://github.com/CERNDocumentServer/cds-rdm/issues/198

search results: render Mathjax in the requests results list

---

.github/workflows/tests.yml
invenio_requests/assets/semantic-ui/js/invenio_requests/InvenioRequestsApp.js
invenio_requests/assets/semantic-ui/js/invenio_requests/components/Buttons.js
invenio_requests/assets/semantic-ui/js/invenio_requests/components/Error.js
invenio_requests/assets/semantic-ui/js/invenio_requests/components/ErrorBoundary.js
invenio_requests/assets/semantic-ui/js/invenio_requests/components/ModalTriggers.js
invenio_requests/assets/semantic-ui/js/invenio_requests/components/RequestsFeed.js
invenio_requests/assets/semantic-ui/js/invenio_requests/components/modals/BaseModal.js
invenio_requests/assets/semantic-ui/js/invenio_requests/components/modals/DeleteConfirmationModal.js
invenio_requests/assets/semantic-ui/js/invenio_requests/contrib/index.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/RequestDetails.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/RequestMetadata.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestAction.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestActionButton.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestActionController.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestActionModal.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestActionModalTrigger.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestActions.js
invenio_requests/assets/semantic-ui/js/invenio_requests/requestsAppInit.js
invenio_requests/assets/semantic-ui/js/invenio_requests/timeline/TimelineFeed.js
invenio_requests/assets/semantic-ui/js/invenio_requests/timelineCommentEditor/state/reducer.js
invenio_requests/assets/semantic-ui/js/invenio_requests/timelineEvents/timelineActionEvents.js

* This will make the package pass the JS tests
* List of [errors and warnings](https://github.com/inveniosoftware/invenio-requests/actions/runs/10247330373/job/28346286782) that is been resolved.
* Note: Copilot AI assisted with these changes, so please review carefully.
**Frontend**
**Reminder** …

linter: fix js linting errors

---

invenio_requests/webpack.py

* closes https://github.com/inveniosoftware/react-searchkit/issues/278

dependencies: update axios

---

invenio_requests/templates/semantic-ui/invenio_requests/details/index.html

When you open many different requests they all have the same `<title>` which is a bad user experience
This PR sets the title to the title of the request
(In this case the different requests all have the same title)
**Frontend**
**Reminder** …

UX: set <title> to request title

---

CHANGES.rst
invenio_requests/__init__.py
invenio_requests/records/models.py
setup.cfg
tests/test_alembic.py

- setup: bump major dependencies
- comp: make compatible to flask-sqlalchemy>=3.1
- fix: sqlalchemy.exc.ArgumentError
- release: v6.0.0.dev1

bump major

---

invenio_requests/notifications/generators.py

- exclude system_user from notifs recipients
- closes CERNDocumentServer/cds-rdm#352

notifs: exclude system_user

---

invenio_requests/assets/semantic-ui/translations/invenio_requests/package-lock.json

translations: update package-lock.json

---

invenio_requests/assets/semantic-ui/js/invenio_requests/contrib/labels/TypeLabel.js
invenio_requests/assets/semantic-ui/js/invenio_requests/search/ComputerTabletRequestItem.js

**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the current repository’s license.

ui: added theme class to request labels

---

invenio_requests/assets/semantic-ui/js/invenio_requests/timeline/TimelineFeed.js
invenio_requests/services/schemas.py
tests/conftest.py

- fix: RemovedInMarshmallow4Warning
- fix: add configuration for tests

fix deprecations

---

invenio_requests/assets/semantic-ui/translations/invenio_requests/package-lock.json

translations: update package-lock.json 

---

invenio_requests/assets/semantic-ui/js/invenio_requests/timeline/TimelineFeed.js

* use async typesetting to allow autolo

MathJax: use async typesetting

---

CHANGES.rst
invenio_requests/__init__.py

release: v6.3.0

---

invenio_requests/assets/semantic-ui/js/invenio_requests/contrib/index.js
invenio_requests/assets/semantic-ui/js/invenio_requests/contrib/labels/TypeLabel.js
invenio_requests/services/requests/facets.py

Add label for `record-deletion` type

labels: add record deletion label

---

CHANGES.rst
invenio_requests/__init__.py

release: v8.0.0

---

CHANGES.rst
invenio_requests/__init__.py
invenio_requests/assets/semantic-ui/js/invenio_requests/request/reviewers/RequestReviewers.js
invenio_requests/assets/semantic-ui/js/invenio_requests/request/reviewers/components/SelectedReviewersList.js
invenio_requests/services/requests/components.py
tests/conftest.py
tests/resources/requests/conftest.py
tests/services/components/test_request_reviewers_component.py
tests/services/requests/test_request_search_permissions.py

closes https://github.com/CERNDocumentServer/cds-rdm/issues/548

reviewers: fix removing the last reviewer
