inveniosoftware/invenio-requests

invenio_requests/records/api.py
Note that this only shadows the metadata system field from the parent class but does not completely remove it (`del Request.metadata` will make the original system field appear again), and accessing `Request.metadata` or `req.metadata` will return `None` rather than raise an `AttributeError`.
It looks like the easiest way of getting rid of this field for good would be to use `invenio_records.api.Record` (and `invenio_records.systemfields.SystemFieldsMixin`) as base class, rather than `invenio_records_resources.record.api.Record` and adding all the other fields defined in the latter class... Though that's a trade-off with duplication of code.
closes #16
=> request: override metadata field with None

invenio_requests/records/api.py, invenio_requests/services/events/service.py, invenio_requests/services/requests/service.py
Because it was awkward to require a RequestsService to fetch a Request object from database via its ID
closes #25
=> requests: move read functionality from service to api class

invenio_requests/customizations/base/actions.py, invenio_requests/customizations/default/actions.py, invenio_requests/resources/events/resources.py, invenio_requests/services/events/service.py, tests/services/events/test_request_events_service.py, tests/services/requests/test_requests_service.py
- Request: comment on submit, accept, cancel and decline; closes #42
- Accept/Decline/Cancel event; closes #28  
- guarantee RequestEvent type immutability via `update`; closes #47 
- alter semantics of delete; closes #46
=> 42 comment on accept decline cancel

invenio_requests/customizations/base/request_types.py, invenio_requests/records/api.py, invenio_requests/records/jsonschemas/requests/definitions-v1.0.0.json, invenio_requests/records/systemfields/entity_reference.py, invenio_requests/services/requests/components.py, invenio_requests/services/requests/config.py, invenio_requests/services/requests/service.py
* add mechanism to RequestType to allow the specification of explicitly allowed reference types (i.e. set of allowed TYPEs in reference dicts) for creators, receivers, and topics
* initialization of entity references was moved to the components, as the initialization via '.create()' did not trigger system fields
closes #36
=> Requests: allow specification of allowed entity reference types

invenio_requests/resources/fields.py, invenio_requests/resources/resource.py, invenio_requests/services/requests/config.py, invenio_requests/services/requests/params.py, invenio_requests/services/requests/service.py, tests/conftest.py, tests/resources/events/test_request_events_resources.py, tests/resources/requests/conftest.py, tests/resources/requests/test_requests_resources.py
* add reference strings (of the shape 'TYPE:ID') as filters for searches
* they are available for the fields 'receiver', 'created_by', and 'topic'
note that this PR doesn't yet allow multiple reference strings for the same field (that is, e.g. `receiver=TYPE:ID` could only be specified once per querystring).
=> search: add filters for entity references

invenio_requests/customizations/base/request_types.py, invenio_requests/registry.py, invenio_requests/services/schemas.py
With this change, a request type can only change the payload schema, and not the entire schema.
=> services: dynamic payload schemas

invenio_requests/customizations/base/request_types.py, invenio_requests/customizations/default/request_types.py, invenio_requests/records/systemfields/request_type.py, invenio_requests/services/requests/results.py, invenio_requests/services/requests/service.py, invenio_requests/services/schemas.py
* only allow a single key to be present
* instead of allowing a fixed set of keys, create the set of accepted keys dynamically based on the request type, similar to the payload
closes #39
=> schemas: construct entity reference schema dynamically

invenio_requests/customizations/base/request_types.py, invenio_requests/customizations/default/request_types.py, invenio_requests/ext.py, tests/customizations/test_request_types.py
* setting class attributes on parent classes would be available on subclasses as well, making the class-based caching approach unviable
* instead, we added a schema cache on the requests flask extension
* also, make the reference types nullable if specified on the request type class
=> request types: add test for schema generation and fix bug

invenio_requests/resolvers/default/records.py, invenio_requests/resolvers/default/requests.py
* When a non-uuid is given to get_record() you get a StatementError
instead of NoResultFoundError. In both cases, we're however just
interested in that a record was not found.
=> resolvers: harmonize no result found exeception

invenio_requests/services/events/service.py, invenio_requests/services/permissions.py, invenio_requests/services/requests/service.py, tests/conftest.py, tests/customizations/test_request_types.py, tests/resources/events/test_request_events_resources.py, tests/resources/requests/test_requests_resources.py, tests/services/requests/test_requests_service.py
add basic request permissions as per discussions
also, add the possibility to have custom permission policies on a per-action (per-request-type) basis (note that this is still pretty rough, and there's no nice mechanism for adding custom permissions to the permission policy in use)
for example, the custom permission check for the `submit` action on the RequestType with `type_id = "invenio-requests.request"` would be: `can_invenio_requests_request_submit = [Disable()]`
=> Permissions: Initial implementations for requests permissions

invenio_requests/customizations/base/request_types.py, invenio_requests/customizations/default/request_types.py, invenio_requests/services/requests/components.py, invenio_requests/services/requests/config.py, tests/customizations/test_request_types.py, tests/services/requests/test_requests_service.py
previously, the status of new requests would be set to `None`, which wasn't exactly what would be expected
=> request types: add default status for new requests

invenio_requests/config.py, invenio_requests/customizations/base/request_types.py, invenio_requests/customizations/default/request_types.py, tests/conftest.py, tests/resources/requests/test_requests_resources.py
since the default request type is only meant to be an example request type (and a good basis for custom request types), we do not actually want to register it during runtime
=> global: do not register default request type

invenio_requests/records/api.py, tests/services/conftest.py, tests/services/events/test_request_events_service.py
closes #74 
* actually, it is always the request ID that's used for external interfaces to interact with requests, and not the number
* thus, there was no real benefit in having Request.get_record resolve by either ID or number
* this only opened up the possibility of having one request's number shadow another request's ID and thus, potential issues
=> api: only have get_record resolve requests by id

invenio_requests/services/requests/service.py
* previously, the requests service would allow permissions for actions
on each request type to be customized via special naming
* the events service however did not use the same lookup logic, so this
could result in inconsistencies regarding permissions
* for now, we want to keep everything as simple as possible; we will
extend the functionality once the need arises
=> service: simplify permission lookup for actions

invenio_requests/services/permissions.py, tests/conftest.py, tests/resources/requests/test_requests_resources.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1315
**Communities OFF**
**Communities ON**
(missing tests)
=> permissions: disable requests when communities not enabled

invenio_requests/assets/semantic-ui/js/invenio_requests/timelineEvent/TimelineEvent.js, invenio_requests/services/events/service.py, invenio_requests/services/schemas.py, tests/resources/events/test_request_events_resources.py
Display edit/delete dropdown only for authorized users.
closes: inveniosoftware/invenio-requests#156
View of the user admin@test.ch
View of the user pablo@gmail.com
=> Permissions: return permissions in request event calls

invenio_requests/assets/semantic-ui/js/invenio_requests/request/state/actions.js, tests/resources/events/test_request_events_resources.py
Because the template can change after an action event it now reloads instead of just refreshing the timeline, also fixes an error on page load when the expanded object is not complete.
needed for https://github.com/inveniosoftware/invenio-app-rdm/pull/1538
partly closes https://github.com/inveniosoftware/invenio-requests/issues/187
=> request timeline: reload instead of refresh on action 

invenio_requests/assets/semantic-ui/js/invenio_requests/components/RequestsFeed.js, invenio_requests/assets/semantic-ui/js/invenio_requests/timeline/TimelineFeed.js, invenio_requests/assets/semantic-ui/js/invenio_requests/timelineCommentEditor/TimelineCommentEditor.js
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1738
Needs PR: https://github.com/inveniosoftware/invenio-app-rdm/pull/1758
The different scenarios (error message, pagination) did not work well with the proposed solution, so I removed the avatar completely from mobile, to give more space to the text box. The avatar on desktop is also slightly smaller than in the mockup, as I reused the `<RequestEventAvatarContainer />`, and was not sure why it should be bigger in the first place (was it intentional? If so, lmk.)
- Removes avatar from mobile
- Fixes sizing bug for avatar on tablet
- Less space between the avatar and the text box on tablet and desktop
=> request feed: fix avatar size and spacing on all screens

invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestActionModalTrigger.js
Closes https://github.com/inveniosoftware/invenio-requests/issues/268
Related to https://github.com/inveniosoftware/invenio-app-rdm/pull/1846
- Reduces default size of request action buttons, to reduce over crowding/clutter in the ui
=> request action modal: reduce default button size

invenio_requests/services/events/service.py, invenio_requests/services/permissions.py
This decouples the permission for creating comments from reading requests, in order to prepare for adding a read-only mode in the repository
=> Add `can_create_comment` permission

CHANGES.rst, invenio_requests/__init__.py, invenio_requests/services/events/service.py, invenio_requests/services/requests/facets.py, setup.cfg
- NOTE: Flask-Security-Invenio invenio-accounts invenio-admin invenio-files-rest invenio-i18n invenio-oauthclient invenio-pidstore invenio-records invenio-records-resources invenio-theme invenio-users-resources have to be released first
=> migrate: flask_babelex replaced by invenio_i18n

invenio_requests/assets/semantic-ui/js/invenio_requests/search/ComputerTabletRequestItem.js, invenio_requests/assets/semantic-ui/js/invenio_requests/search/MobileRequestItem.js
Closes https://github.com/inveniosoftware/invenio-communities/issues/953
**NOTE:** The ghost icon is not available in SUI, so I had to go with the secret user icon (ref https://github.com/inveniosoftware/rfcs/pull/71#discussion_r1178090454).
=> RequestItem: add icon for deleted communities

MANIFEST.in, invenio_requests/notifications/__init__.py, invenio_requests/notifications/builders.py, invenio_requests/notifications/filters.py, invenio_requests/notifications/generators.py, invenio_requests/services/events/service.py, invenio_requests/templates/semantic-ui/invenio_notifications/comment-request-event.create.jinja, setup.cfg, tests/conftest.py, tests/customizations/test_request_types.py, tests/resources/requests/conftest.py, tests/services/conftest.py, tests/services/events/test_request_events_service.py, tests/services/requests/test_request_search_permissions.py, tests/services/requests/test_requests_service.py
A new recipient generator takes care of fetching all users participating in a request. A notification operation is only triggered if the request event is a comment.
closes #304 
Add notification to be sent when creating a comment on a request. This will trigger on every request comment (e.g. community invitation, community submission). Recipients will be users who have taken part in the request so far, without the user creating the comment.
The requests package does not know about communities, so we can not use the community member recipient generator to fetch certain members (e.g. owners, managers). This can be overridden in `app-rdm` if required.
**Third-party …
=> notifications: add comment request event notification

invenio_requests/assets/semantic-ui/js/invenio_requests/InvenioRequestsApp.js, invenio_requests/assets/semantic-ui/js/invenio_requests/request/Request.js, invenio_requests/assets/semantic-ui/js/invenio_requests/request/RequestDetails.js, invenio_requests/assets/semantic-ui/js/invenio_requests/requestsAppInit.js, invenio_requests/assets/semantic-ui/js/invenio_requests/timeline/TimelineFeed.js, invenio_requests/services/requests/components.py, invenio_requests/templates/semantic-ui/invenio_requests/details/index.html
* add an overridable for the timeline header
* inject permissions prop
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1395
NOTE: the permissions for request.payload updation should be handled in separate PR (this TODO https://github.com/inveniosoftware/invenio-requests/pull/343/files#diff-4b568e443f92c06d4ea44587cf21b1134cfaff1f5bf4ceb88076ae894c452f0fR44)
The task is already created: https://github.com/inveniosoftware/invenio-rdm-records/issues/1402
=> access request: update guest request payload

invenio_requests/services/user_moderation/errors.py, invenio_requests/services/user_moderation/service.py, tests/services/user_moderation/test_user_moderation_service.py
closes https://github.com/inveniosoftware/invenio-requests/issues/344
=> moderation: restrict request duplication.

invenio_requests/assets/semantic-ui/js/invenio_requests/request/RequestMetadata.js
Closes https://github.com/zenodo/rdm-project/issues/590
Adds the record link to the bottom right if request is accepted.
=> request metadata: add record link

invenio_requests/records/mappings/os-v1/requestevents/requestevent-v1.0.0.json, invenio_requests/records/mappings/os-v1/requests/request-v1.0.0.json, invenio_requests/records/mappings/os-v2/requestevents/requestevent-v1.0.0.json, invenio_requests/records/mappings/os-v2/requests/request-v1.0.0.json, invenio_requests/records/mappings/v7/requestevents/requestevent-v1.0.0.json, invenio_requests/records/mappings/v7/requests/request-v1.0.0.json
- The mapping is stored as a string/enum in ES/OS. Using the same type
makes sure the mapping comparison is correct when performing a
mapping update.
=> mappings: change "dynamic" values to string

invenio_requests/ext.py
closes https://github.com/zenodo/zenodo-rdm/issues/891 
❓  why this is needed
We have a request type that is configurable. Right now, the request types can be added via entry points so we had to modify the logic of the entry point load to accommodate the use case.  
The change is backwards compatible.
=> registry: allow entry pointsto be callables

invenio_requests/assets/semantic-ui/js/invenio_requests/timelineCommentEditor/TimelineCommentEditor.js, invenio_requests/assets/semantic-ui/js/invenio_requests/timelineEvents/TimelineCommentEvent.js
* These changes depends on: https://github.com/inveniosoftware/react-invenio-forms/pull/244
* Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2730
* Align property naming as RichEditior wrongly named value instead of initialValue
* Change `onChange` to `onEditorChange` as recommended in the `tinymce` docs.
* Change the prop `value` to `inputValue`, as `value` seems to conflict with other elements, causing the input text in edit mode to behave oddly.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedepend …
=> Requests Comment: fix jumping cursor 

.github/workflows/tests.yml, invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestAction.js
* Closes https://github.com/inveniosoftware/invenio-requests/pull/398
* Closes https://github.com/inveniosoftware/invenio-requests/pull/396
**Frontend**
**Reminder**
1. You license your contribution under the …
=> comments: fix comment editor loses content on focus change

CHANGES.rst, invenio_requests/__init__.py, invenio_requests/assets/semantic-ui/js/invenio_requests/request/actions/RequestAction.js
Backport of https://github.com/inveniosoftware/invenio-requests/pull/400 to 4.1.x
=> Editor content loss backport

invenio_requests/assets/semantic-ui/js/invenio_requests/timeline/TimelineFeed.js
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/133
=> timeline feed: render mathematical content in the request comments

invenio_requests/services/requests/service.py
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/203
=> requests: manage sending notifications

babel.ini
* Currently when you run `python setup.py extract_messages` it will Not include `*.jinja` template files.
This PR fix that.
**Frontend**
**Reminder**
1. You license your contribution under the same terms as the …
=> i18n: include jinja file encoding in babel.ini

invenio_requests/services/requests/facets.py
I have gone through all the existing requests and added the three which were missing (subcommunity, user moderation and legacy record upgrade). 
I have also reordered and grouped them so that it is clear what request they refer to, as the label can be unclear. This grouping will be helpful for the eventual refactoring I mention in the following
**Context:**
For a request to display a proper type label in the request sidebar and in search facets, they must be defined in invenio-requests globally. This isn't great design as site-specific request types must be put into this module which should be unaware.
* If you have added …
=> requests: add missing facets and reorder

invenio_requests/assets/semantic-ui/js/invenio_requests/contrib/Icons.js, invenio_requests/assets/semantic-ui/js/invenio_requests/contrib/index.js, invenio_requests/assets/semantic-ui/js/invenio_requests/contrib/labels/TypeLabel.js, invenio_requests/assets/semantic-ui/js/invenio_requests/requestsAppInit.js, invenio_requests/assets/semantic-ui/js/invenio_requests/search/ComputerTabletRequestItem.js, invenio_requests/assets/semantic-ui/js/invenio_requests/search/MobileRequestItem.js, invenio_requests/services/requests/facets.py
Close https://github.com/zenodo/zenodo-rdm/issues/1061
---
---
second commit
**Frontend**
**Reminder**
1. You license your contribution under the same terms as the …
=> UI: add subcommunity invitation facet and label

invenio_requests/customizations/request_types.py, invenio_requests/services/events/service.py
Close https://github.com/inveniosoftware/invenio-requests/issues/417
**Frontend**
**Reminder**
1. You license your contribution under the same terms as the current …
=> config: allow comment notification builder to be custom

CHANGES.rst, invenio_requests/__init__.py, invenio_requests/records/models.py, setup.cfg, tests/test_alembic.py
- Depends on https://github.com/inveniosoftware/invenio-users-resources/pull/156 and `7.0.0` release
- **setup: bump major dependencies** 
- **comp: make compatible to flask-sqlalchemy>=3.1**
- **fix: sqlalchemy.exc.ArgumentError**
* Textual SQL expression 'SELECT setval(pg_get_seri...' should be
explicitly declared as text('SELECT setval(pg_get_seri...')
- **release: v6.0.0.dev1**
- **installation: bump invenio-users-resources**
=> Flask v3 upgrade

.gitignore, CHANGES.rst, invenio_requests/__init__.py, invenio_requests/assets/semantic-ui/js/invenio_requests/components/SharedOrMineFilter.js, invenio_requests/assets/semantic-ui/js/invenio_requests/search/RequestStatusFilterComponent.js, invenio_requests/assets/semantic-ui/js/invenio_requests/search/RequestsSearchLayout.js, invenio_requests/customizations/request_types.py, invenio_requests/records/api.py, invenio_requests/resources/requests/config.py, invenio_requests/services/generators.py, invenio_requests/services/permissions.py, invenio_requests/services/requests/config.py, invenio_requests/services/requests/params.py, invenio_requests/services/requests/service.py
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1948
=> requests: split mine and shared with me

invenio_requests/assets/semantic-ui/translations/invenio_requests/messages/index.js
Remove depreciated languages from index
**Frontend**
**Reminder** …
=> message-index: remove depreciated languages

invenio_requests/services/events/config.py, invenio_requests/services/requests/results.py
Sometimes, keys relevant to the serialization process are not included inside ``_source``, i.e. "highlight." By adding ``hit.meta`` as part of the serializer context, we make them available without the risk of name collision.
=> services: include Opensearch meta in the results

invenio_requests/services/requests/service.py
=> fix: extra filter not needed param

.github/workflows/pypi-publish.yml, .github/workflows/tests.yml, CHANGES.rst, invenio_requests/__init__.py, invenio_requests/webpack.py
* due to security venerability in axios see: https://github.com/axios/axios/issues/6463
**Frontend**
**Reminder**
2. You agree that you have the …
=> Fix-axios-version

invenio_requests/ext.py
Replaced `importlib_metadata` and `importlib_resources` with `importlib`.
* Using invenio_base.utils.entry_points for entry_points
**Frontend**
**Reminder**
2. You agree that you have the …
=> chores: replaced importlib_xyz with importlib

invenio_requests/services/requests/results.py
* partial backport of #431
* previously, `has_permissions_to()` was reused from the parent class, which passed the request object as `record` only
* some permission generators expect the request to be available under the name `request` however
=> [Backport] pass request as kwarg to permission machinery

invenio_requests/services/events/config.py, invenio_requests/services/events/service.py, tests/services/events/test_request_events_service.py
Adds service component calls to the `create`, `update`, and `delete` methods of the RequestEventsService class, since it lacked them. Also adds a config variable that provides a configurable list of service components via the service's config class.
**Frontend**
**Reminder**
1. …
=> Adding component calls to RequestEventsService methods
